#!/usr/bin/env bash
# Regenerates the README demo images in demo/ — every one produced entirely by
# ImageMagick, using the same recipes the skill documents (see
# skills/imagemagick/references/generative.md). Run from anywhere; writes into
# the repo's demo/ directory.

set -eu

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEMO="$REPO/demo"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$DEMO"
cd "$WORK"

FONT=DejaVu-Sans
FONT_BOLD=DejaVu-Sans-Bold
magick -list font | grep -q "Font: $FONT_BOLD" || { FONT=helvetica; FONT_BOLD=helvetica-bold; }

# --- 1. Banner: synthwave sunset — striped sun, perspective neon grid,
#     neon-glow title, CRT scanlines. Every layer is drawn from primitives.
# sky: deep space fading to a hot horizon
magick -size 1200x118 gradient:'#0d0221-#3b0f5e' \
  \( -size 1200x50 gradient:'#3b0f5e-#c2255c' \) -append +repage sky.png
# sun: vertical gradient disc, lower half sliced by widening stripes
magick -size 170x170 gradient:'#ffe66d-#ff2a6d' sun_grad.png
magick -size 170x170 xc:black -fill white -draw 'circle 85,85 85,3' -fill black \
  -draw 'rectangle 0,100 170,104' -draw 'rectangle 0,115 170,121' \
  -draw 'rectangle 0,132 170,140' -draw 'rectangle 0,151 170,161' sun_mask.png
magick sun_grad.png sun_mask.png -alpha off -compose copy_opacity -composite sun.png
# grid floor: flat neon grid, perspective-converged toward the horizon, self-glow
v=""; for x in $(seq 0 60 1200); do v="$v line $x,0 $x,400"; done
h=""; for y in 0 40 90 150 220 300 396; do h="$h line 0,$y 1200,$y"; done
magick -size 1200x400 xc:'#0d0221' -stroke '#ff2a6d' -strokewidth 3 -draw "$v $h" grid_flat.png
magick grid_flat.png -virtual-pixel background -background '#0d0221' \
  -distort Perspective '0,0 480,0  1200,0 720,0  0,400 -900,92  1200,400 2100,92' \
  -crop 1200x92+0+0 +repage grid_persp.png
magick grid_persp.png \( +clone -blur 0x4 \) -compose screen -composite grid.png
# neon title: white core over stacked magenta/cyan blurred clones
magick -background none -font "$FONT_BOLD" -pointsize 58 -fill white \
  -stroke '#ffd9ec' -strokewidth 1 label:'imagemagick plugin' title_core.png
magick title_core.png \
  \( +clone -channel RGBA -fill '#ff2a6d' -colorize 100 +channel -blur 0x14 \) \
  \( +clone -channel RGBA -fill '#ff2a6d' -colorize 100 +channel -blur 0x14 \) \
  \( +clone -channel RGBA -fill '#05d9e8' -colorize 100 +channel -blur 0x5 \) \
  -reverse -background none -compose screen -layers merge +repage \
  title_core.png -compose over -gravity center -composite title.png
# scanlines: 1x3 dark-line tile expanded across the banner
magick -size 1x3 xc:none -fill 'rgba(13,2,33,0.28)' -draw 'point 0,0' -write mpr:scan +delete \
  -size 1200x260 tile:mpr:scan scan.png
# scrim: darken the sky behind the text block so the type pops off the sun
magick -size 1200x150 gradient:'rgba(13,2,33,0.55)-rgba(13,2,33,0)' scrim.png
# assemble
magick sky.png sun.png -gravity north -geometry +290+30 -composite \
  scrim.png -gravity north -geometry +0+0 -composite grid.png -append +repage \
  title.png -gravity north -geometry +0+30 -composite \
  -font "$FONT" -pointsize 22 -gravity north -fill 'rgba(13,2,33,0.9)' \
  -annotate +1+120 'ImageMagick expertise for Claude Code' \
  -fill '#a5f8ff' \
  -annotate +0+118 'ImageMagick expertise for Claude Code' \
  -gravity south -pointsize 14 -fill 'rgba(13,2,33,0.9)' \
  -annotate +1+9 'every image in this README was generated by ImageMagick, from nothing' \
  -fill '#ffe3f2' \
  -annotate +0+10 'every image in this README was generated by ImageMagick, from nothing' \
  scan.png -gravity center -compose over -composite \
  -quality 92 "$DEMO/banner.jpg"

# --- 2. A base "photo" synthesized from primitives: sky, sun, mountains.
magick -size 320x240 gradient:'#ffd9a0-#355c7d' -rotate 180 \
  -fill '#fff3b0' -draw 'circle 230,70 230,44' \
  -fill '#2a3d45' -draw 'polygon 0,240 0,170 90,110 150,180 200,140 320,210 320,240' \
  -fill '#1c2b30' -draw 'polygon 0,240 110,190 190,220 320,230 320,240' \
  -attenuate 0.3 +noise Gaussian -quality 92 scene.jpg

# --- 3. Effects montage: the generative.md recipes applied to the base scene.
magick scene.jpg fx_original.png
magick scene.jpg -sepia-tone 80% fx_sepia.png
magick scene.jpg -bordercolor snow -background black +polaroid fx_polaroid.png
magick scene.jpg \( +clone -fill black -colorize 100 -fill white \
  -draw 'circle 160,120 160,40' -blur 0x30 \) -compose multiply -composite fx_vignette.png
magick scene.jpg \( +clone -threshold 50% -spread 8 -blur 0x1 \) \
  -alpha off -compose copy_opacity -composite fx_torn.png
magick scene.jpg -virtual-pixel transparent -background none \
  -distort Barrel '0.0 0.0 0.12' fx_barrel.png

magick montage \
  -label original   fx_original.png \
  -label sepia      fx_sepia.png \
  -label +polaroid  fx_polaroid.png \
  -label vignette   fx_vignette.png \
  -label 'torn edges' fx_torn.png \
  -label '-distort Barrel' fx_barrel.png \
  -tile 3x2 -geometry +8+8 -background '#f4f4f4' -font "$FONT" -pointsize 16 \
  -depth 8 -quality 90 "$DEMO/effects.jpg"

# --- 4. The flagship worked example: the README itself, typeset and thrown
#     on the desk as a loose stack of pages.
"$REPO/skills/imagemagick/scripts/paper-stack.sh" "$REPO/README.md" stack-full.png 3
magick stack-full.png -resize 520x "$DEMO/paper-stack.png"

# --- 5. A seamless landscape panorama drawn from primitives, then wrapped into
#     a "tiny planet" by tiny-planet.sh. Seamless = purely vertical sky (every
#     column identical) and ridgelines whose y matches at x=0 and x=W, so the
#     Polar wrap joins with no radial seam at 12 o'clock.
magick -size 1400x420 gradient:'#6fb2e0-#fbe6c0' pano_a.png
magick pano_a.png \
  -fill '#9fb6c8' -draw 'polygon 0,420 0,215 180,196 360,232 560,188 780,224 980,192 1180,228 1220,205 1400,215 1400,420' \
  -fill '#6f8ba0' -draw 'polygon 0,420 0,272 220,252 430,285 640,246 900,286 1120,250 1330,284 1400,272 1400,420' \
  -fill '#37504f' -draw 'polygon 0,420 0,318 260,300 520,324 760,298 1020,324 1260,300 1400,318 1400,420' \
  pano_b.png
magick -size 1400x150 gradient:'#43682f-#1f3318' -attenuate 0.5 +noise Gaussian pano_ground.png
trees=""; x=20; while [ "$x" -lt 1400 ]; do trees="$trees polygon $x,30 $((x-9)),56 $((x+9)),56"; x=$((x+46)); done
magick pano_ground.png -fill '#28421f' -draw "$trees" pano_ground2.png
magick pano_b.png pano_ground2.png -gravity south -compose over -composite \
  -attenuate 0.2 +noise Gaussian -quality 92 pano.jpg
"$REPO/skills/imagemagick/scripts/tiny-planet.sh" pano.jpg planet.png 700
magick pano.jpg -resize 660x pano_disp.png
magick planet.png -resize 380x380 -background '#f4f4f4' -gravity center -extent 660x380 planet_disp.png
magick montage \
  -label 'seamless 1400x420 panorama — sky, ridgelines, treeline, all from primitives' pano_disp.png \
  -label 'wrapped by  magick ... -distort Polar 0   (tiny-planet.sh)' planet_disp.png \
  -tile 1x2 -geometry +12+12 -background '#f4f4f4' -font "$FONT" -pointsize 15 -fill '#333' \
  -quality 90 "$DEMO/tiny-planet.jpg"

# --- 6. The four vignette.sh presets on a crop of that panorama.
magick pano.jpg -gravity center -resize '420x300^' -extent 420x300 vbase.jpg
for p in soft dark white grunge; do
  "$REPO/skills/imagemagick/scripts/vignette.sh" vbase.jpg "vg_$p.jpg" "$p"
done
magick montage -label soft vg_soft.jpg -label dark vg_dark.jpg \
  -label white vg_white.jpg -label grunge vg_grunge.jpg \
  -tile 2x2 -geometry +8+8 -background '#f4f4f4' -font "$FONT" -pointsize 16 \
  -quality 90 "$DEMO/vignettes.jpg"

# --- 7. Built-in geometric distortions on a legible grid — the -distort/-swirl/
#     -implode/-wave family made obvious. The yellow dot is a fixed reference.
g=""; for i in $(seq 0 30 300); do g="$g line $i,0 $i,300 line 0,$i 300,$i"; done
magick -size 300x300 gradient:'#5b7cc7-#c66fa8' -stroke white -strokewidth 2 -draw "$g" \
  -fill '#ffe169' -stroke none -draw 'circle 150,150 150,124' dgrid.png
magick dgrid.png -virtual-pixel transparent -background none -distort Arc 120 d_arc.png
magick dgrid.png -swirl 200 d_swirl.png
magick dgrid.png -implode 0.7 d_implode.png
magick dgrid.png -background none -wave 10x120 d_wave.png
magick dgrid.png -virtual-pixel edge -distort Polar 0 d_polar.png
magick dgrid.png -virtual-pixel transparent -background none -distort Barrel '0.0 0.0 -0.35' d_pin.png
magick montage \
  -label '-distort Arc' d_arc.png -label '-swirl' d_swirl.png -label '-implode' d_implode.png \
  -label '-wave' d_wave.png -label '-distort Polar' d_polar.png -label '-distort Barrel' d_pin.png \
  -tile 3x2 -geometry '200x200+8+8>' -background '#f4f4f4' -font "$FONT" -pointsize 16 \
  -quality 90 "$DEMO/distortions.jpg"

magick identify "$DEMO"/*
du -h "$DEMO"/* | sort -k2
