#!/usr/bin/env bash
# Regenerates the README demo images in demo/ — every one produced entirely by
# ImageMagick, using the same recipes the skill documents (see
# skills/imagemagick/references/generative.md). Run from anywhere; writes into
# the repo's demo/ directory.

set -eu

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEMO="$REPO/demo"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$DEMO"
cd "$WORK"

FONT=DejaVu-Sans
FONT_BOLD=DejaVu-Sans-Bold
magick -list font | grep -q "Font: $FONT_BOLD" || { FONT=helvetica; FONT_BOLD=helvetica-bold; }

# --- 1. Banner: radial gradient, softlight plasma clouds, annotated title.
magick -size 1200x260 radial-gradient:'#2a6f97-#0b1d33' \
  \( -size 1200x260 plasma:fractal -blur 0x3 -colorspace Gray -auto-level \) \
  -compose softlight -composite \
  -font "$FONT_BOLD" -pointsize 58 -fill white -stroke '#0b1d33' -strokewidth 2 \
  -gravity center -annotate +0-36 'imagemagick plugin' \
  -stroke none -font "$FONT" -pointsize 24 -fill '#cfe8ff' \
  -annotate +0+28 'ImageMagick expertise for Claude Code' \
  -pointsize 19 -fill '#8fb8d8' \
  -annotate +0+66 'every image in this README was generated by ImageMagick, from nothing' \
  -quality 92 "$DEMO/banner.jpg"

# --- 2. A base "photo" synthesized from primitives: sky, sun, mountains.
magick -size 320x240 gradient:'#ffd9a0-#355c7d' -rotate 180 \
  -fill '#fff3b0' -draw 'circle 230,70 230,44' \
  -fill '#2a3d45' -draw 'polygon 0,240 0,170 90,110 150,180 200,140 320,210 320,240' \
  -fill '#1c2b30' -draw 'polygon 0,240 110,190 190,220 320,230 320,240' \
  -attenuate 0.3 +noise Gaussian -quality 92 scene.jpg

# --- 3. Effects montage: the generative.md recipes applied to the base scene.
magick scene.jpg fx_original.png
magick scene.jpg -sepia-tone 80% fx_sepia.png
magick scene.jpg -bordercolor snow -background black +polaroid fx_polaroid.png
magick scene.jpg \( +clone -fill black -colorize 100 -fill white \
  -draw 'circle 160,120 160,40' -blur 0x30 \) -compose multiply -composite fx_vignette.png
magick scene.jpg \( +clone -threshold 50% -spread 8 -blur 0x1 \) \
  -alpha off -compose copy_opacity -composite fx_torn.png
magick scene.jpg -virtual-pixel transparent -background none \
  -distort Barrel '0.0 0.0 0.12' fx_barrel.png

magick montage \
  -label original   fx_original.png \
  -label sepia      fx_sepia.png \
  -label +polaroid  fx_polaroid.png \
  -label vignette   fx_vignette.png \
  -label 'torn edges' fx_torn.png \
  -label '-distort Barrel' fx_barrel.png \
  -tile 3x2 -geometry +8+8 -background '#f4f4f4' -font "$FONT" -pointsize 16 \
  -depth 8 -quality 90 "$DEMO/effects.jpg"

# --- 4. The flagship worked example: plain text -> folded-letter photo.
cat > letter.txt <<'EOF'
Dear reader,

This page began life as a plain .txt file. ImageMagick
typeset it, creased it with gradient lighting, warped it
into perspective, and photographed it onto your screen --
no graphics editor was opened in the making of this image.

Yours procedurally,
  magick(1)
EOF
"$REPO/skills/imagemagick/scripts/fold-paper.sh" letter.txt folded-full.png
magick folded-full.png -resize 460x "$DEMO/fold-paper.png"

magick identify "$DEMO"/*
du -h "$DEMO"/* | sort -k2
