#!/usr/bin/env bash
# Regenerates the README demo images in demo/ — every one produced entirely by
# ImageMagick, using the same recipes the skill documents (see
# skills/imagemagick/references/generative.md). Run from anywhere; writes into
# the repo's demo/ directory.

set -eu

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEMO="$REPO/demo"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$DEMO"
cd "$WORK"

FONT=DejaVu-Sans
FONT_BOLD=DejaVu-Sans-Bold
magick -list font | grep -q "Font: $FONT_BOLD" || { FONT=helvetica; FONT_BOLD=helvetica-bold; }

# --- 1. Banner: synthwave sunset — striped sun, perspective neon grid,
#     neon-glow title, CRT scanlines. Every layer is drawn from primitives.
# sky: deep space fading to a hot horizon
magick -size 1200x118 gradient:'#0d0221-#3b0f5e' \
  \( -size 1200x50 gradient:'#3b0f5e-#c2255c' \) -append +repage sky.png
# sun: vertical gradient disc, lower half sliced by widening stripes
magick -size 170x170 gradient:'#ffe66d-#ff2a6d' sun_grad.png
magick -size 170x170 xc:black -fill white -draw 'circle 85,85 85,3' -fill black \
  -draw 'rectangle 0,100 170,104' -draw 'rectangle 0,115 170,121' \
  -draw 'rectangle 0,132 170,140' -draw 'rectangle 0,151 170,161' sun_mask.png
magick sun_grad.png sun_mask.png -alpha off -compose copy_opacity -composite sun.png
# grid floor: flat neon grid, perspective-converged toward the horizon, self-glow
v=""; for x in $(seq 0 60 1200); do v="$v line $x,0 $x,400"; done
h=""; for y in 0 40 90 150 220 300 396; do h="$h line 0,$y 1200,$y"; done
magick -size 1200x400 xc:'#0d0221' -stroke '#ff2a6d' -strokewidth 3 -draw "$v $h" grid_flat.png
magick grid_flat.png -virtual-pixel background -background '#0d0221' \
  -distort Perspective '0,0 480,0  1200,0 720,0  0,400 -900,92  1200,400 2100,92' \
  -crop 1200x92+0+0 +repage grid_persp.png
magick grid_persp.png \( +clone -blur 0x4 \) -compose screen -composite grid.png
# neon title: white core over stacked magenta/cyan blurred clones
magick -background none -font "$FONT_BOLD" -pointsize 58 -fill white \
  -stroke '#ffd9ec' -strokewidth 1 label:'imagemagick plugin' title_core.png
magick title_core.png \
  \( +clone -channel RGBA -fill '#ff2a6d' -colorize 100 +channel -blur 0x14 \) \
  \( +clone -channel RGBA -fill '#ff2a6d' -colorize 100 +channel -blur 0x14 \) \
  \( +clone -channel RGBA -fill '#05d9e8' -colorize 100 +channel -blur 0x5 \) \
  -reverse -background none -compose screen -layers merge +repage \
  title_core.png -compose over -gravity center -composite title.png
# scanlines: 1x3 dark-line tile expanded across the banner
magick -size 1x3 xc:none -fill 'rgba(13,2,33,0.28)' -draw 'point 0,0' -write mpr:scan +delete \
  -size 1200x260 tile:mpr:scan scan.png
# scrim: darken the sky behind the text block so the type pops off the sun
magick -size 1200x150 gradient:'rgba(13,2,33,0.55)-rgba(13,2,33,0)' scrim.png
# assemble
magick sky.png sun.png -gravity north -geometry +290+30 -composite \
  scrim.png -gravity north -geometry +0+0 -composite grid.png -append +repage \
  title.png -gravity north -geometry +0+30 -composite \
  -font "$FONT" -pointsize 22 -gravity north -fill 'rgba(13,2,33,0.9)' \
  -annotate +1+120 'ImageMagick expertise for Claude Code' \
  -fill '#a5f8ff' \
  -annotate +0+118 'ImageMagick expertise for Claude Code' \
  -gravity south -pointsize 14 -fill 'rgba(13,2,33,0.9)' \
  -annotate +1+9 'every image in this README was generated by ImageMagick, from nothing' \
  -fill '#ffe3f2' \
  -annotate +0+10 'every image in this README was generated by ImageMagick, from nothing' \
  scan.png -gravity center -compose over -composite \
  -quality 92 "$DEMO/banner.jpg"

# --- 2. A base "photo" synthesized from primitives: sky, sun, mountains.
magick -size 320x240 gradient:'#ffd9a0-#355c7d' -rotate 180 \
  -fill '#fff3b0' -draw 'circle 230,70 230,44' \
  -fill '#2a3d45' -draw 'polygon 0,240 0,170 90,110 150,180 200,140 320,210 320,240' \
  -fill '#1c2b30' -draw 'polygon 0,240 110,190 190,220 320,230 320,240' \
  -attenuate 0.3 +noise Gaussian -quality 92 scene.jpg

# --- 3. Effects montage: the generative.md recipes applied to the base scene.
magick scene.jpg fx_original.png
magick scene.jpg -sepia-tone 80% fx_sepia.png
magick scene.jpg -bordercolor snow -background black +polaroid fx_polaroid.png
magick scene.jpg \( +clone -fill black -colorize 100 -fill white \
  -draw 'circle 160,120 160,40' -blur 0x30 \) -compose multiply -composite fx_vignette.png
magick scene.jpg \( +clone -threshold 50% -spread 8 -blur 0x1 \) \
  -alpha off -compose copy_opacity -composite fx_torn.png
magick scene.jpg -virtual-pixel transparent -background none \
  -distort Barrel '0.0 0.0 0.12' fx_barrel.png

magick montage \
  -label original   fx_original.png \
  -label sepia      fx_sepia.png \
  -label +polaroid  fx_polaroid.png \
  -label vignette   fx_vignette.png \
  -label 'torn edges' fx_torn.png \
  -label '-distort Barrel' fx_barrel.png \
  -tile 3x2 -geometry +8+8 -background '#f4f4f4' -font "$FONT" -pointsize 16 \
  -depth 8 -quality 90 "$DEMO/effects.jpg"

# --- 4. The flagship worked example: the README itself, typeset and thrown
#     on the desk as a loose stack of pages.
"$REPO/skills/imagemagick/scripts/paper-stack.sh" "$REPO/README.md" stack-full.png 3
magick stack-full.png -resize 520x "$DEMO/paper-stack.png"

magick identify "$DEMO"/*
du -h "$DEMO"/* | sort -k2
